#!/bin/bash
clear
start=$(date +"%T")
printf "Build start : $start\r\n"
cp src/indices/index.plus.js src/index.js

export NODE_ENV=production
cp src/config/customizations/env.production.hiveeye .env.production

npm run build
end=$(date +"%T")
COLOR='\033[0;36m'
printf "${COLOR}Build end : $end\r\n"
